spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=data01
    username: user01
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 600000
      minimum-idle: 1
      idle-timeout: 1200000
      connection-timeout: 600000
      maximum-pool-size: 3
      pool-name: user-hikari-cp
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
logging:
  level:
    '[com.zaxxer.hikari]': WARN
    org:
      springframework:
        security: WARN
      hibernate:
        sql: WARN
        type:
          descriptor:
            sql: WARN
  file:
    name: logs/user_authn.log