spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      leak-detection-threshold: 600000
      minimum-idle: ${CP_MIN_IDLE:1}
      idle-timeout: 1200000
      connection-timeout: 600000
      maximum-pool-size: ${CP_MAX_SIZE:3}
      pool-name: ${CP_NAME:user-hikari-cp}
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
logging:
  level:
    '[com.zaxxer.hikari]': WARN
    org:
      springframework:
        security: WARN
      hibernate:
        sql: WARN
        type:
          descriptor:
            sql: WARN
  file:
    name: logs/user_authn.log