spring:
  profiles:
    default: dev
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: ${APP_NAME:user-auth-n}
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/postgres?currentSchema=data01
  #   username: user01
  #   password: 123456
  #   driver-class-name: org.postgresql.Driver
  #   hikari:
  #     leak-detection-threshold: 600000
  #     minimum-idle: 1
  #     idle-timeout: 1200000
  #     connection-timeout: 600000
  #     maximum-pool-size: 3
  #     pool-name: user-hikari-cp

  # jpa:
  #   generate-ddl: false
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       '[format_sql]': true

  # security:
  #   user:
  #     name: user
  #     password: 1234

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        same-site: strict


jwt:
  expiration:
    access-token: ${ACCESS_TOKEN_EXP:180000}
    refresh-token: ${ACCESS_TOKEN_EXP:604800000}
  algorithm: ${JWT_ALG:HmacSHA256}
  key-size: 2048
        
# logging:
#   level:
#     '[com.zaxxer.hikari]': DEBUG
#     org:
#       springframework:
#         security: DEBUG
#       hibernate:
#         sql: DEBUG
#         type:
#           descriptor:
#             sql: DEBUG
#   file:
#     name: logs/user_authn.log