services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    user: '0:0'
    restart: no
    env_file: 
      - .env
    ports:
      - "5050:80"
    volumes:
      - ./.data:/var/lib/pgadmin
    networks: 
      - docker_net
networks:
  docker_net:
    external: true