services:
  kafka-1:
    image: apache/kafka-native:latest
    container_name: kafka-container-1
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: ADtnaiSRRY2t2i7uFGEr9Q
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:29092,CONTROLLER://kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3 
      KAFKA_LOG_RETENTION_HOURS: 24 
    networks:
      - docker_net
    volumes:
      - /home/xflier/kafka/data/kafka-1:/var/lib/kafka/data
  kafka-2:
    image: apache/kafka-native:latest
    container_name: kafka-container-2
    ports:
      - "39092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      CLUSTER_ID: ADtnaiSRRY2t2i7uFGEr9Q
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://localhost:39092,CONTROLLER://kafka-2:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3 
      KAFKA_LOG_RETENTION_HOURS: 24 
    volumes:
       - /home/xflier/kafka/data/kafka-1:/var/lib/kafka/data
    networks:
      - docker_net
  kafka-3:
    image: apache/kafka-native:latest
    container_name: kafka-container-3
    ports:
      - "49092:9092"
    environment:
      KAFKA_BROKER_ID: 3
      CLUSTER_ID: ADtnaiSRRY2t2i7uFGEr9Q
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092,PLAINTEXT_HOST://localhost:49092,CONTROLLER://kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3 
      # KAFKA_LOG_DIR: /home/xflier/kafka/logs/kafka-3
      KAFKA_LOG_RETENTION_HOURS: 24 
    volumes:
      - /home/xflier/kafka/data/kafka-3:/var/lib/kafka/data
    networks:
      - docker_net
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui-container
  #   ports:
  #     - "58080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: kafka-cluster
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
  #     DYNAMIC_CONFIGURATION_ENABLED: "true"
  #   networks:
  #     - docker_net
  #   depends_on:
  #     - kafka-1
  #     - kafka-2
  #     - kafka-3
networks:
  docker_net:
    external: true